name: Ubuntu SSH to GitHub Action

on:
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git Config
      run: |
        git config --global user.name "JaswantTeja"
        git config --global user.email "sunnyteja201@gmail.com"
        git config --global --list
        git config --global credential.helper store
        echo "${{ secrets.ACCOUNT_TOKEN }}" > .git-credentials
    - name: SSH Keepalive Hack
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
- name: Start SSH via tmate
  continue-on-error: true
  timeout-minutes: 350
  uses: P3TERX/ssh2actions@main
  # Send connection info to Telegram (optional)
  # You can find related documents here: https://core.telegram.org/bots
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
